CREATE TABLE notification_templates (
    id                     BIGINT NOT NULL AUTO_INCREMENT,
    message                LONGTEXT,
    message_to             VARCHAR(255),
    subject                VARCHAR(500),
    message_body           LONGTEXT,
    email_to               VARCHAR(500),
    email_cc               VARCHAR(500),
    email_bcc              VARCHAR(500),
    email_reply_to         VARCHAR(255),
    template               VARCHAR(500),
    is_sms                 INT,
    is_email               INT,
    is_whatsapp            INT,
    whatsapp_template_name VARCHAR(255),
    whatsapp_template_body LONGTEXT,
    additional_data        VARCHAR(1000),
    dlt_template_id        VARCHAR(255),
    template_group_id      BIGINT,
    created_by             BIGINT,
    updated_by             BIGINT,
    created_at             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at             TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
